### ISSUE TITLE
[Part 3] 

### ISSUE THREAD

**Issue by nishu767** [TheWCKD/blocFromZeroToHero#8]
![image](https://user-images.githubusercontent.com/56351087/156552618-542ae1f9-2744-40b9-aae0-8e9733fb3ed1.png)

CounterState({@required this.counterValue,  this.wasIncremented});

this shows an error and it works fine when i remove '@' from required, it also asks to add required to 'this.wasIncremented' .
means  CounterState({required this.counterValue, required this.wasIncremented}); works fine ,
 but in counter_cubit it asks to pass the required parameter of 'this.wasIncremented' in countercubit()

**Comment by nishu767** [comment]
is it same as 

part of 'counter_cubit.dart';

class CounterState {
  int counterValue;
  bool wasIncremented;

  CounterState({
    required this.counterValue,
    this.wasIncremented = true,
  });
}

**Comment by IgorMagal** [comment]
That's because of dart's null safety feature, the way i worked around it was adding a ? to the variable wasIncremented like this:

class CounterState extends Equatable{
  int counterValue;
  **bool? wasIncremented;**
  CounterState({
    required this.counterValue,
    this.wasIncremented,
  });

  @override 
  List<Object?> get props => [counterValue,wasIncremented];
}
